from aiogram.dispatcher.filters.state import StatesGroup, State


class FSM(StatesGroup):
    Question_1 = State()
    Question_2 = State()
    Question_3 = State()
    Question_4 = State()
    Question_5 = State()
    Question_6 = State()
    Question_7 = State()
    Question_8 = State()
    Question_9 = State()
    Question_10 = State()
    Question_11 = State()
    Question_12 = State()
    Question_13 = State()
    Question_14 = State()
    Question_15 = State()
    Question_16 = State()
    Question_17 = State()
    Question_18 = State()
    Question_19 = State()
    Question_20 = State()
    Question_21 = State()
    Question_22 = State()
    Question_23 = State()
    Question_24 = State()
    Question_25 = State()
    Question_26 = State()
    Question_27 = State()
    Question_28 = State()
    Question_29 = State()
    Question_30 = State()
    Question_31 = State()
    Question_32 = State()
    Question_33 = State()
    Question_34 = State()
